@startuml c2-mcearl-v1

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Container Diagram\nMcEarl v1\nMinecraft Classic Server in Erlang/OTP

AddRelTag("dashed", $lineStyle = DashedLine())

Person(client, "Client", "Plays Multiplayer")
Person(admin, "Admin", "Administers")

System_Boundary(boundary, "McEarl") {
	Container(server, "Server", "Container: Erlang Distributed Application")
	ContainerDb(db, "Distributed Database", "Container: Mnesia")
}
System_Ext(classicube, "Classicube", "Hosts the server list")

Rel(client, server, "connects via", $tags=dashed")
Rel(admin, server, "connects via", $tags=dashed")
Rel(server, classicube, "sends heartbeat packets to")
Rel(server, db, "reads from & writes to")

LAYOUT_WITH_LEGEND()
@enduml
