@startuml c3-server-v2

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Component Diagram\nMcEarl v2\nServer Peer Node
AddRelTag("dashed", $lineStyle = DashedLine())

Container_Boundary(boundary, "Server Peer Node") {
	Component(mcearl_sup, "Master Supervisor", "Component: Erlang Supervisor Actor")
	Component(logger, "Logger", "Component: Erlang Worker Actor")
	Component(player_sup, "Player Supervisor", "Component: Erlang Supervisor Actor")
	Component(client1Comp, "Player Communicator", "Component: Erlang Worker Actor")
	Component(client2Comp, "Player Communicator", "Component: Erlang Worker Actor")
	Component(client3Comp, "Player Communicator", "Component: Erlang Worker Actor")
}

Container_Ext(origin, "Origin Node", "Container: Erlang Application")
ContainerDb_Ext(db, "Distributed Database", "Container: Mnesia")

Rel(origin, mcearl_sup, "offloads connections to")
Rel(mcearl_sup, logger, "supervises")
Rel(mcearl_sup, player_sup, "supervises")
Rel(player_sup, client1Comp, "supervises")
Rel(player_sup, client2Comp, "supervises")
Rel(player_sup, client3Comp, "supervises")
Rel(client1Comp, db, "reads from & writes to")
Rel(client2Comp, db, "reads from & writes to")
Rel(client3Comp, db, "reads from & writes to")

LAYOUT_WITH_LEGEND()
@enduml
