@startuml c3-server-v1

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Component Diagram\nMcEarl v1\nServer
AddRelTag("dashed", $lineStyle = DashedLine())

Person(client, "Client", "Plays Multiplayer")
Person(admin, "Admin", "Administers")

Container_Boundary(boundary, "Server") {
	Component(masterSup, "Master Supervisor", "Component: Erlang Supervisor Actor")
	Component(logger, "Logger", "Component: Erlang Worker Actor")
	Component(listen, "TCP Listener", "Component: Erlang Worker Actor")
	Component(heartbeat, "Heartbeat", "Component: Erlang Worker Actor")
	Component(clientSup, "Client Supervisor", "Component: Erlang Supervisor Actor")
	Component(clientComp, "Client Communicator", "Component: Erlang Worker Actor")
	Component(adminSup, "Admin Supervisor", "Component: Erlang Supervisor Actor")
	Component(adminComp, "Server Communicator", "Component: Erlang Worker Actor")
}

System_Ext(classicube, "Clssicube", "Hosts the server list")
ContainerDb_Ext(db, "Distributed Database", "Container: Mnesia")

Rel_D(client, listen, "connects via")
Rel_D(admin, listen, "connects via")
Rel(heartbeat, classicube, "sends heartbeat packets to")
Rel(masterSup, logger, "supervises")
Rel(masterSup, clientSup, "supervises")
Rel(masterSup, adminSup, "supervises")
Rel(masterSup, listen, "supervises")
Rel(masterSup, heartbeat, "supervises")
Rel(clientSup, clientComp, "supervises")
Rel(clientComp, db, "reads from & writes to")
Rel_U(clientComp, client, "communicates with")
Rel(adminSup, adminComp, "supervises")
Rel_U(adminComp, admin, "communicates with")
Rel(adminComp, db, "reads from & writes to")

LAYOUT_WITH_LEGEND()
@enduml
