@startuml c3-server-v1

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Component Diagram\nMcEarl v1\nServer
AddRelTag("dashed", $lineStyle = DashedLine())

Person(client, "Client", "Plays Multiplayer")
Person(admin, "Admin", "Administers")

Container_Boundary(boundary, "Server") {
	Component(mcearl_sup, "Master Supervisor", "Component: Erlang Supervisor Actor")
	Component(logger, "Logger", "Component: Erlang Worker Actor")
	Component(player_man, "Player Manager", "Component: Erlang Worker Actor")
	Component(heartbeat, "Heartbeat", "Component: Erlang Worker Actor")
	Component(player_sup, "Player Supervisor", "Component: Erlang Supervisor Actor")
	Component(player_serv, "Player Communicator", "Component: Erlang Worker Actor")
	Component(admin_sup, "Admin Supervisor", "Component: Erlang Supervisor Actor")
	Component(admin_serv, "Admin Communicator", "Component: Erlang Worker Actor")
}

System_Ext(classicube, "Clssicube", "Hosts the server list")
ContainerDb_Ext(db, "Distributed Database", "Container: Mnesia")

Rel_D(client, player_man, "connects via")
Rel_D(admin, player_man, "connects via")
Rel(heartbeat, classicube, "sends heartbeat packets to")
Rel(mcearl_sup, logger, "supervises")
Rel(mcearl_sup, player_sup, "supervises")
Rel(mcearl_sup, admin_sup, "supervises")
Rel(mcearl_sup, player_man, "supervises")
Rel(mcearl_sup, heartbeat, "supervises")
Rel(player_sup, player_serv, "supervises")
Rel(player_serv, db, "reads from & writes to")
Rel_U(player_serv, client, "communicates with")
Rel(admin_sup, admin_serv, "supervises")
Rel_U(admin_serv, admin, "communicates with")
Rel(admin_serv, db, "reads from & writes to")

LAYOUT_WITH_LEGEND()
@enduml
