@startuml

actor Player as player

box "McEarl Origin Node"
entity Ranch as ranch
entity Proxy as proxy
entity "Controller Manager" as controller_man
entity "Controller Supervisor" as controller_sup
entity Controller as controller
end box

box "McEarl Peer Node"
entity "Server Manager" as server_man
entity "Server Supervisor" as server_sup
entity Server as server
end box

database Mnesia as mnesia

player -> ranch : connect
ranch -> proxy : delegates
proxy -> controller_man : asks for an available server
controller_man -> controller_sup: spawns new node controllers
controller_sup -> controller : supervises
controller -> server_man : asks for an available server
server_man -> server_sup : spawns new servers
server_sup -> server: supervises
server_man -> server : asks for an available server
server_man -> controller: returns available server pid
controller -> controller_man: returns available server pid
controller_man -> proxy : returns an available server pid

loop
	player <-> proxy : communicate
	proxy <-> server : communicate
	server <-> server : update
	server -> mnesia : write to
end

@enduml
