@startuml mcearl

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title System Context Diagram\nMcEarl\nMinecraft Classic Server in Erlang/OTP

Person(client, "Client", "Plays Multiplayer")
Person(admin, "Admin", "Administers")

System(mcearl, "McEarl", "Minecraft Clasic Server")
System_Ext(classicube, "Classicube", "Hosts the server list")

Rel(client, mcearl, "connects to")
Rel(admin, mcearl, "connects to")
Rel(mcearl, classicube, "sends heartbeat packets to")

LAYOUT_WITH_LEGEND()
@enduml
